[package]
name = "chip8_interpreter" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Katrina <enby@egg.com>"]
edition = '2018'

[dependencies]
text_io = "0.1.8"
rand = "0.7.3"
sdl2 = "0.33.0"
maplit = "1.0.2"

